name: car_servicing
description: "App for car maintenance"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  form_field_validator: ^1.0.1
  image_picker: ^1.0.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  shelf: ^1.3.0
  shelf_router: ^1.0.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
